// Maps every raw QuickDraw-style model label to one of ScribblePark's
// park-friendly big categories. Lookup is case-insensitive — lowercase
// the incoming label before checking this map.
//
// Categories in use:
//   flower, tree, bush, mushroom   — plants (sway/pulse animation)
//   rabbit                          — general land animal (hop/travel)
//   toad                            — pond-edge amphibian/reptile (hop)
//   bug                             — small crawling/scuttling creature
//   snail                           — slow ground glider
//   butterfly                       — small flying insect
//   bird                            — larger flying creature
//   fish                            — pond swimmer
//   duck                            — pond-surface paddler
//   landfill                        — anything that doesn't belong in a
//                                      park at all (objects, food, body
//                                      parts, vehicles, buildings, etc.)
//
// Grouping is based on movement/behavior, not visual resemblance —
// e.g. whale/dolphin -> fish (so they swim), bat -> bird (so it flies).

export const CATEGORY_MAP = {
  "aircraft carrier": "landfill",
  "airplane": "landfill",
  "alarm clock": "landfill",
  "ambulance": "landfill",
  "angel": "landfill",
  "animal migration": "bird",
  "ant": "bug",
  "anvil": "landfill",
  "apple": "landfill",
  "arm": "landfill",
  "asparagus": "landfill",
  "axe": "landfill",
  "backpack": "landfill",
  "banana": "landfill",
  "bandage": "landfill",
  "barn": "landfill",
  "baseball": "landfill",
  "baseball bat": "landfill",
  "basket": "landfill",
  "basketball": "landfill",
  "bat": "bird",
  "bathtub": "landfill",
  "beach": "landfill",
  "bear": "rabbit",
  "beard": "landfill",
  "bed": "landfill",
  "bee": "butterfly",
  "belt": "landfill",
  "bench": "landfill",
  "bicycle": "landfill",
  "binoculars": "landfill",
  "bird": "bird",
  "birthday cake": "landfill",
  "blackberry": "landfill",
  "blueberry": "landfill",
  "book": "landfill",
  "boomerang": "landfill",
  "bottlecap": "landfill",
  "bowtie": "landfill",
  "bracelet": "landfill",
  "brain": "landfill",
  "bread": "landfill",
  "bridge": "landfill",
  "broccoli": "bush",
  "broom": "landfill",
  "bucket": "landfill",
  "bulldozer": "landfill",
  "bus": "landfill",
  "bush": "bush",
  "butterfly": "butterfly",
  "cactus": "bush",
  "cake": "landfill",
  "calculator": "landfill",
  "calendar": "landfill",
  "camel": "rabbit",
  "camera": "landfill",
  "camouflage": "landfill",
  "campfire": "landfill",
  "candle": "landfill",
  "cannon": "landfill",
  "canoe": "landfill",
  "car": "landfill",
  "carrot": "landfill",
  "castle": "landfill",
  "cat": "rabbit",
  "ceiling fan": "landfill",
  "cello": "landfill",
  "cell phone": "landfill",
  "chair": "landfill",
  "chandelier": "landfill",
  "church": "landfill",
  "circle": "landfill",
  "clarinet": "landfill",
  "clock": "landfill",
  "cloud": "landfill",
  "coffee cup": "landfill",
  "compass": "landfill",
  "computer": "landfill",
  "cookie": "landfill",
  "cooler": "landfill",
  "couch": "landfill",
  "cow": "rabbit",
  "crab": "bug",
  "crayon": "landfill",
  "crocodile": "toad",
  "crown": "landfill",
  "cruise ship": "landfill",
  "cup": "landfill",
  "diamond": "landfill",
  "dishwasher": "landfill",
  "diving board": "landfill",
  "dog": "rabbit",
  "dolphin": "fish",
  "donut": "landfill",
  "door": "landfill",
  "dragon": "landfill",
  "dresser": "landfill",
  "drill": "landfill",
  "drums": "landfill",
  "duck": "duck",
  "dumbbell": "landfill",
  "ear": "landfill",
  "elbow": "landfill",
  "elephant": "rabbit",
  "envelope": "landfill",
  "eraser": "landfill",
  "eye": "landfill",
  "eyeglasses": "landfill",
  "face": "landfill",
  "fan": "landfill",
  "feather": "landfill",
  "fence": "landfill",
  "finger": "landfill",
  "fire hydrant": "landfill",
  "fireplace": "landfill",
  "firetruck": "landfill",
  "fish": "fish",
  "flamingo": "bird",
  "flashlight": "landfill",
  "flip flops": "landfill",
  "floor lamp": "landfill",
  "flower": "flower",
  "flying saucer": "landfill",
  "foot": "landfill",
  "fork": "landfill",
  "frog": "toad",
  "frying pan": "landfill",
  "garden": "flower",
  "garden hose": "landfill",
  "giraffe": "rabbit",
  "goatee": "landfill",
  "golf club": "landfill",
  "grapes": "landfill",
  "grass": "bush",
  "guitar": "landfill",
  "hamburger": "landfill",
  "hammer": "landfill",
  "hand": "landfill",
  "harp": "landfill",
  "hat": "landfill",
  "headphones": "landfill",
  "hedgehog": "rabbit",
  "helicopter": "landfill",
  "helmet": "landfill",
  "hexagon": "landfill",
  "hockey puck": "landfill",
  "hockey stick": "landfill",
  "horse": "rabbit",
  "hospital": "landfill",
  "hot air balloon": "landfill",
  "hot dog": "landfill",
  "hot tub": "landfill",
  "hourglass": "landfill",
  "house": "landfill",
  "house plant": "bush",
  "hurricane": "landfill",
  "ice cream": "landfill",
  "jacket": "landfill",
  "jail": "landfill",
  "kangaroo": "rabbit",
  "key": "landfill",
  "keyboard": "landfill",
  "knee": "landfill",
  "knife": "landfill",
  "ladder": "landfill",
  "lantern": "landfill",
  "laptop": "landfill",
  "leaf": "bush",
  "leg": "landfill",
  "light bulb": "landfill",
  "lighter": "landfill",
  "lighthouse": "landfill",
  "lightning": "landfill",
  "line": "landfill",
  "lion": "rabbit",
  "lipstick": "landfill",
  "lobster": "bug",
  "lollipop": "landfill",
  "mailbox": "landfill",
  "map": "landfill",
  "marker": "landfill",
  "matches": "landfill",
  "megaphone": "landfill",
  "mermaid": "landfill",
  "microphone": "landfill",
  "microwave": "landfill",
  "monkey": "rabbit",
  "moon": "landfill",
  "mosquito": "bug",
  "motorbike": "landfill",
  "mountain": "landfill",
  "mouse": "rabbit",
  "moustache": "landfill",
  "mouth": "landfill",
  "mug": "landfill",
  "mushroom": "mushroom",
  "nail": "landfill",
  "necklace": "landfill",
  "nose": "landfill",
  "ocean": "landfill",
  "octagon": "landfill",
  "octopus": "fish",
  "onion": "landfill",
  "oven": "landfill",
  "owl": "bird",
  "paintbrush": "landfill",
  "paint can": "landfill",
  "palm tree": "tree",
  "panda": "rabbit",
  "pants": "landfill",
  "paper clip": "landfill",
  "parachute": "landfill",
  "parrot": "bird",
  "passport": "landfill",
  "peanut": "landfill",
  "pear": "landfill",
  "peas": "landfill",
  "pencil": "landfill",
  "penguin": "bird",
  "piano": "landfill",
  "pickup truck": "landfill",
  "picture frame": "landfill",
  "pig": "rabbit",
  "pillow": "landfill",
  "pineapple": "landfill",
  "pizza": "landfill",
  "pliers": "landfill",
  "police car": "landfill",
  "pond": "landfill",
  "pool": "landfill",
  "popsicle": "landfill",
  "postcard": "landfill",
  "potato": "landfill",
  "power outlet": "landfill",
  "purse": "landfill",
  "rabbit": "rabbit",
  "raccoon": "rabbit",
  "radio": "landfill",
  "rain": "landfill",
  "rainbow": "landfill",
  "rake": "landfill",
  "remote control": "landfill",
  "rhinoceros": "rabbit",
  "rifle": "landfill",
  "river": "landfill",
  "roller coaster": "landfill",
  "rollerskates": "landfill",
  "sailboat": "landfill",
  "sandwich": "landfill",
  "saw": "landfill",
  "saxophone": "landfill",
  "school bus": "landfill",
  "see saw": "landfill",
  "scissors": "landfill",
  "scorpion": "bug",
  "screwdriver": "landfill",
  "sea turtle": "fish",
  "shark": "fish",
  "sheep": "rabbit",
  "shoe": "landfill",
  "shorts": "landfill",
  "shovel": "landfill",
  "sink": "landfill",
  "skateboard": "landfill",
  "skull": "landfill",
  "skyscraper": "landfill",
  "sleeping bag": "landfill",
  "smiley face": "landfill",
  "snail": "snail",
  "snake": "toad",
  "snorkel": "landfill",
  "snowflake": "landfill",
  "snowman": "landfill",
  "soccer ball": "landfill",
  "sock": "landfill",
  "speedboat": "landfill",
  "spider": "bug",
  "spoon": "landfill",
  "spreadsheet": "landfill",
  "square": "landfill",
  "squiggle": "landfill",
  "squirrel": "rabbit",
  "stairs": "landfill",
  "star": "landfill",
  "steak": "landfill",
  "stereo": "landfill",
  "stethoscope": "landfill",
  "stitches": "landfill",
  "stop sign": "landfill",
  "stove": "landfill",
  "strawberry": "landfill",
  "streetlight": "landfill",
  "string bean": "landfill",
  "submarine": "landfill",
  "suitcase": "landfill",
  "sun": "landfill",
  "swan": "duck",
  "sweater": "landfill",
  "swing set": "landfill",
  "sword": "landfill",
  "syringe": "landfill",
  "table": "landfill",
  "teapot": "landfill",
  "teddy-bear": "landfill",
  "telephone": "landfill",
  "television": "landfill",
  "tennis racquet": "landfill",
  "tent": "landfill",
  "the eiffel tower": "landfill",
  "the great wall of china": "landfill",
  "the mona lisa": "landfill",
  "tiger": "rabbit",
  "toaster": "landfill",
  "toe": "landfill",
  "toilet": "landfill",
  "tooth": "landfill",
  "toothbrush": "landfill",
  "toothpaste": "landfill",
  "tornado": "landfill",
  "tractor": "landfill",
  "traffic light": "landfill",
  "train": "landfill",
  "tree": "tree",
  "triangle": "landfill",
  "trombone": "landfill",
  "truck": "landfill",
  "trumpet": "landfill",
  "t-shirt": "landfill",
  "umbrella": "landfill",
  "underwear": "landfill",
  "van": "landfill",
  "vase": "landfill",
  "violin": "landfill",
  "washing machine": "landfill",
  "watermelon": "landfill",
  "waterslide": "landfill",
  "whale": "fish",
  "wheel": "landfill",
  "windmill": "landfill",
  "wine bottle": "landfill",
  "wine glass": "landfill",
  "wristwatch": "landfill",
  "yoga": "landfill",
  "zebra": "rabbit",
  "zigzag": "landfill",
};

const FALLBACK_KEYWORDS = [
  { category: "flower", keywords: ["flower", "rose", "daisy", "blossom", "petal", "tulip", "sunflower", "bloom", "garden", "plant"] },
  { category: "tree", keywords: ["tree", "pine", "oak", "palm", "leaf", "branch", "forest"] },
  { category: "bush", keywords: ["bush", "shrub", "grass", "cactus", "hedge", "fern", "weed"] },
  { category: "mushroom", keywords: ["mushroom", "fungus", "toadstool"] },
  { category: "rabbit", keywords: ["rabbit", "dog", "cat", "bear", "lion", "tiger", "monkey", "mouse", "cow", "horse", "sheep", "pig", "elephant", "zebra", "camel", "giraffe", "kangaroo", "panda", "raccoon", "hedgehog", "squirrel", "fox", "wolf", "deer"] },
  { category: "toad", keywords: ["frog", "toad", "snake", "crocodile", "alligator", "lizard"] },
  { category: "bug", keywords: ["bug", "ant", "bee", "spider", "crab", "lobster", "scorpion", "mosquito", "beetle", "insect"] },
  { category: "snail", keywords: ["snail", "slug"] },
  { category: "butterfly", keywords: ["butterfly", "moth", "dragonfly"] },
  { category: "bird", keywords: ["bird", "bat", "owl", "parrot", "penguin", "flamingo", "duck", "swan", "eagle", "hawk"] },
  { category: "fish", keywords: ["fish", "whale", "dolphin", "octopus", "shark", "sea turtle", "turtle"] },
  { category: "duck", keywords: ["duck", "swan"] },
];

function normalizeLabel(rawLabel) {
  if (!rawLabel || typeof rawLabel !== "string") return "";

  return rawLabel
    .toLowerCase()
    .trim()
    .replace(/[_-]+/g, " ")
    .replace(/[^\w\s]/g, " ")
    .replace(/\s+/g, " ");
}

// Looks up a raw model label (any casing) and returns one of the big
// park categories, falling back to "landfill" for anything unmapped.
export function mapToCategory(rawLabel) {
  const normalized = normalizeLabel(rawLabel);

  if (!normalized) return "landfill";

  if (CATEGORY_MAP[normalized]) {
    return CATEGORY_MAP[normalized];
  }

  for (const { category, keywords } of FALLBACK_KEYWORDS) {
    if (keywords.some((keyword) => normalized.includes(keyword))) {
      return category;
    }
  }

  return "landfill";
}

export function resolveCategory(rawLabel, predictions = []) {
  const directCategory = mapToCategory(rawLabel);

  if (directCategory !== "landfill") {
    return directCategory;
  }

  const rankedMatches = (predictions || [])
    .map((prediction) => {
      const label = prediction?.label || prediction?.name || prediction;
      const scoreValue = Number(prediction?.score ?? prediction?.confidence ?? 0);
      const score = Number.isFinite(scoreValue) ? scoreValue : 0;
      const category = mapToCategory(label);

      return {
        category,
        score,
      };
    })
    .filter(({ category }) => category && category !== "landfill");

  if (rankedMatches.length === 0) {
    return directCategory;
  }

  rankedMatches.sort((a, b) => b.score - a.score);
  return rankedMatches[0]?.category || directCategory;
}
